##############################################################################
#                                                                            #
# This is the config file for deadline submission in scene Bundle. Changing  #
# contents of this file with change deadline submission behaviour on all     #
# bundles made henceforth                                                    #
#                                                                            #
# Modify only if you understand                                              #
#                                                                            #
#                                                                            #
# This is yaml format ... indentation is important ... avoid using TABs      #
#                                                                            #
#                                                                            #
# Copyright 2015, ICE Animations (Pvt.) Ltd.                                 #
#                                                                            #
##############################################################################


##############################################################################
#                              default settings                              #
##############################################################################

#default submission settings
chunkSize: 50
ignoreDefaultCamera: false
priority: 25
submitAsSuspended: false
submitEachCamera: false
submitEachRenderLayer: true
submitSceneFile: false

#default job filtering settings
#illegal_layer_names: [.*depth.*]
illegal_layer_names: []
illegal_camera_names: []

#default path and name settings
#variable names can be bundle_base, project, episode, sequence, shot, name
output_base: '\\renders2\Storage\Projects\external'
bundle_loc: '%(bundle_base)s\%(project)s\%(episode)s\%(sequence)s\%(shot)s'
output_loc: '%(output_base)s\%(project)s\02_production\%(episode)s\%(sequence)s\%(shot)s'
job_name: '%(project)s_%(episode)s_%(sequence)s_%(shot)s - %(name)s'

#default pool to basepath mapping
pools:
  none: #exact name of pool as in deadline
    # bases are the location that a bundle must be copied
    bases: [\\hp-001\drive1, \\hp-001\drive2, \\hp-001\drive3]

    # in case of more than one base, one shall be chosen randomly
    ## methods from [random_choice, user_sequential]
    base_selection: random_choice 
secondaryPool: none

# pool select methods from [random_choice, user_sequential, min_frames_pending]
pool_selection: random_choice


##############################################################################
#                                 overrides                                  #
##############################################################################

# Overrides are applied on default settings in order on the conditions
# mentioned. In case of overlap between them, overrides mentioned later will
# prevail
#
# Conditions:
# [<conditionType>, <matchMethod>, <value>]
#
# Conditions can be nested as lists in lists
# Use match_any as a condition when OR is required between sibling conditions
# otherwise match_all (AND) is assumed
#
# conditionTypes from [renderer, project, episode, shot, sequence, name]
#
# matchMethods from ['eq', 'in', 'contains', 'not in', 'not contains',
# 'startswith', 'not startswith', 'endswith', 'not endswith', 'matches',
# 'not matches']
#
# [renderer, arnold] is equivalent to [renderer, eq, arnold]
#
#
# Examples:
#
# Settings for Even number episode of Project Suntop
# - conditions:
#   - [project, 'Suntop']
#   - [
#       [episode, 'matches', '(?i)ep0?02'],
#       [episode, 'matches', '(?i)ep0?04'],
#       [episode, 'matches', '(?i)ep0?06'],
#       [episode, 'matches', '(?i)ep0?08'],
#       [episode, 'matches', '(?i)ep0?10'],
#       match_any
#     ]
#   # match_all # (* assumed)
#   settings:
#     pools:
#       suntop02:
#         bases: [\\hp-001\drive1, \\hp-001\drive2, \\hp-001\drive3]
#         base_selection: user_sequential
#     output_base: '\\renders\Storage\Projects\external'
#

overrides:

#######################
#  General Overrides  #
#######################

# Case if renderer is redshift
- conditions:
  - [renderer, redshift]
  settings:
    pools:
      redshift:
        bases: [\\hp-001\drive1, \\hp-001\drive2, \\hp-001\drive3]
        base_selection: random_choice
    pool_selection: user_sequential

# Case if renderer is arnold
- conditions:
  - [renderer, arnold]
  settings:
    pools:
      arnold:
        bases: [\\hp-001\drive1, \\hp-001\drive2, \\hp-001\drive3]
        base_selection: random_choice
    chunkSize: 15

#############################
#  Project based Overrides  #
#############################

#- conditions:
  #- [project, 'Cocomo_2018']
  #settings:
    #output_loc: '%(output_base)s\%(project)s\02_production\new_renders\%(episode)s\%(sequence)s\%(shot)s'


# For Suntop odd numbered episodes use \\renders2 and suntop01
- conditions:
  - [project, 'Suntop_S02']
  - [
      [episode, 'matches', '(?i)ep0?01$'],
      [episode, 'matches', '(?i)ep0?03$'],
      [episode, 'matches', '(?i)ep0?05$'],
      [episode, 'matches', '(?i)ep0?07$'],
      [episode, 'matches', '(?i)ep0?09$'],
      [episode, 'matches', '(?i)ep0?11$'],
      match_any
    ]
  settings:
    pools:
      suntop01:
        bases: [\\hp-001\drive1, \\hp-001\drive2, \\hp-001\drive3]
        base_selection: user_sequential
    secondaryPool: suntop
    output_base: '\\renders3\Storage\Projects\external'

# For Suntop even numbered episodes use \\renders and suntop02
- conditions:
  - [project, 'Suntop_S02']
  - [
      [episode, 'matches', '(?i)ep0?02$'],
      [episode, 'matches', '(?i)ep0?04$'],
      [episode, 'matches', '(?i)ep0?06$'],
      [episode, 'matches', '(?i)ep0?08$'],
      [episode, 'matches', '(?i)ep0?10$'],
      [episode, 'matches', '(?i)ep0?12$'],
      match_any
    ]
  settings:
    pools:
      suntop02:
        bases: [\\hp-001\drive1, \\hp-001\drive2, \\hp-001\drive3]
        base_selection: user_sequential
    secondaryPool: suntop
    output_base: '\\renders4\Storage\Projects\external'

- conditions:
  - [project, 'Kid_Song']
  settings:
    pools:
      kidssongs:
        bases: [\\hp-001\drive1, \\hp-001\drive2, \\hp-001\drive3]
        base_selection: user_sequential
    secondaryPool: redshift


- conditions:
  - [project, 'DingDong_Magik']
  settings:
    pools:
      dingdong:
        bases: [\\hp-001\drive1, \\hp-001\drive2, \\hp-001\drive3]
        base_selection: user_sequential
    secondaryPool: redshift

- conditions:
  - [project, 'Prince_Choc_5']
  settings:
    pools:
      prince:
        bases: [\\hp-001\drive1, \\hp-001\drive2, \\hp-001\drive3]
        base_selection: user_sequential
    secondaryPool: redshift

- conditions:
  - [project, 'Knorr_Gameshow_S2']
  settings:
    pools:
      knorr:
        bases: [\\hp-001\drive1, \\hp-001\drive2, \\hp-001\drive3]
        base_selection: user_sequential
    secondaryPool: redshift

- conditions:
  - [project, 'Feel_Better']
  settings:
    pools:
      feelbetter:
        bases: [\\hp-001\drive1, \\hp-001\drive2, \\hp-001\drive3]
        base_selection: user_sequential
    secondaryPool: redshift
